name: trigger-daily-email

on:
  schedule:
    - cron: "0 * * * *"   # toutes les heures UTC
  workflow_dispatch: {}

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call /send endpoint
        env:
          API_URL: ${{ secrets.API_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          TICKERS: ${{ secrets.TICKERS }}
        run: |
          set -e
          if [ -z "$TICKERS" ]; then
            curl -sS -X POST "$API_URL" -H "X-API-Key: $API_KEY"
          else
            curl -sS -X POST "$API_URL?tickers=$TICKERS" -H "X-API-Key: $API_KEY"
          fi
